name: master_thesis
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py311h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - biopython==1.86
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - datasets==4.5.0
      - dill==0.4.0
      - einops==0.8.2
      - filelock==3.20.3
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.7
      - idna==3.11
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - networkx==3.6.1
      - numpy==2.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pandas==3.0.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - protobuf==6.33.5
      - pyarrow==23.0.0
      - pybigwig==0.3.25
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyfaidx==0.9.0.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.1
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - sentry-sdk==2.51.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tokenizers==0.22.2
      - torch==2.5.1+cu124
      - torchaudio==2.5.1+cu124
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu124
      - tqdm==4.67.3
      - transformers==5.0.0
      - triton==3.1.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - wandb==0.24.1
      - xxhash==3.6.0
      - yarl==1.22.0
